#!/usr/bin/env bash
# =============================================================================
# Cinder Runtime — hot-swap.sh
# Applies non-JVM preset settings to the live runtime config file.
#
# Usage:
#   ./hot-swap.sh --preset <name> [--runtime-file <path>]
#
# Notes:
#   - This does not restart the JVM.
#   - CinderServer polls the runtime config file periodically and applies updates.
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${CINDER_BASE_DIR:="${SCRIPT_DIR}/../.."}"
: "${CINDER_PRESET_DIR:="${SCRIPT_DIR}/../presets"}"
: "${CINDER_RUNTIME_CONFIG_FILE:="${CINDER_BASE_DIR}/runtime-active.conf"}"

PRESET=""

usage() {
    cat <<'EOF'
Usage: hot-swap.sh --preset <name> [--runtime-file <path>]

Options:
  --preset <name>         Preset to apply (survival, event, low-power, benchmark, extreme)
  --runtime-file <path>   Override runtime config file path
  -h, --help              Show this help text
EOF
}

resolve_preset_file() {
    local preset_name="$1"
    local candidates=(
        "${CINDER_PRESET_DIR}/${preset_name}.conf"
        "${CINDER_BASE_DIR}/presets/${preset_name}.conf"
        "${CINDER_BASE_DIR}/${preset_name}.conf"
    )

    local candidate
    for candidate in "${candidates[@]}"; do
        if [[ -f "${candidate}" ]]; then
            echo "${candidate}"
            return 0
        fi
    done

    return 1
}

read_existing_value() {
    local key="$1"
    local fallback="$2"
    local escaped_key="${key//./\\.}"

    if [[ ! -f "${CINDER_RUNTIME_CONFIG_FILE}" ]]; then
        echo "${fallback}"
        return 0
    fi

    local line
    line="$(grep -E "^${escaped_key}=" "${CINDER_RUNTIME_CONFIG_FILE}" | tail -n 1 || true)"
    if [[ -z "${line}" ]]; then
        echo "${fallback}"
    else
        echo "${line#*=}"
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --preset)
            PRESET="$2"
            shift 2
            ;;
        --runtime-file)
            CINDER_RUNTIME_CONFIG_FILE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[hot-swap] Unknown argument: $1" >&2
            usage
            exit 1
            ;;
    esac
done

if [[ -z "${PRESET}" ]]; then
    echo "[hot-swap] --preset is required" >&2
    usage
    exit 1
fi

PRESET_FILE="$(resolve_preset_file "${PRESET}")" || {
    echo "[hot-swap] Preset not found: ${PRESET}" >&2
    exit 1
}

# shellcheck source=/dev/null
source "${PRESET_FILE}"

if [[ -z "${CINDER_CHUNK_CACHE_SIZE:-}" ]]; then
    CINDER_CHUNK_CACHE_SIZE="$(read_existing_value "cinder.chunk.cacheSize" "256")"
fi
if [[ -z "${CINDER_ENTITY_DEFERRED_INTERVAL:-}" ]]; then
    CINDER_ENTITY_DEFERRED_INTERVAL="$(read_existing_value "cinder.entity.deferredInterval" "4")"
fi
if [[ -z "${CINDER_VIEW_DISTANCE:-}" ]]; then
    CINDER_VIEW_DISTANCE="$(read_existing_value "cinder.viewDistance" "8")"
fi
if [[ -z "${CINDER_SIMULATION_DISTANCE:-}" ]]; then
    CINDER_SIMULATION_DISTANCE="$(read_existing_value "cinder.simulationDistance" "${CINDER_VIEW_DISTANCE}")"
fi
if [[ -z "${CINDER_SAVE_INTERVAL_TICKS:-}" ]]; then
    CINDER_SAVE_INTERVAL_TICKS="$(read_existing_value "cinder.saveIntervalTicks" "1")"
fi

if (( CINDER_SIMULATION_DISTANCE > CINDER_VIEW_DISTANCE )); then
    CINDER_SIMULATION_DISTANCE="${CINDER_VIEW_DISTANCE}"
fi

mkdir -p "$(dirname "${CINDER_RUNTIME_CONFIG_FILE}")"
TMP_FILE="${CINDER_RUNTIME_CONFIG_FILE}.tmp"

cat > "${TMP_FILE}" <<EOF
# Auto-generated by hot-swap.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source preset: ${PRESET} (${PRESET_FILE})
cinder.chunk.cacheSize=${CINDER_CHUNK_CACHE_SIZE}
cinder.entity.deferredInterval=${CINDER_ENTITY_DEFERRED_INTERVAL}
cinder.viewDistance=${CINDER_VIEW_DISTANCE}
cinder.simulationDistance=${CINDER_SIMULATION_DISTANCE}
cinder.saveIntervalTicks=${CINDER_SAVE_INTERVAL_TICKS}
EOF

mv "${TMP_FILE}" "${CINDER_RUNTIME_CONFIG_FILE}"

echo "[hot-swap] Applied preset '${PRESET}' to ${CINDER_RUNTIME_CONFIG_FILE}"
echo "[hot-swap] chunk.cacheSize=${CINDER_CHUNK_CACHE_SIZE} deferredInterval=${CINDER_ENTITY_DEFERRED_INTERVAL} view=${CINDER_VIEW_DISTANCE} sim=${CINDER_SIMULATION_DISTANCE} saveInterval=${CINDER_SAVE_INTERVAL_TICKS}"
echo "[hot-swap] Changes will be applied by CinderServer on the next runtime config poll cycle."
